title: "Jelena Mićić"
description: "Nezvanična informativna stranica o Jeleni Mićić, najboljoj kadetkinji Medicinskog fakulteta VMA generacije 2026."
lang: sr-Latn
url: "https://dazdejkovic.github.io"
baseurl: "/jelena-micic"
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
